<a href="https://colab.research.google.com/github/amitpoa/-Assignment_20231079/blob/main/HOMEWORK_%5BPandas_and_NumPy_Exercise_for_Data_Analysis%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy Array Exercises**

In [ ]:
# Create a Numpy array filled with all zeros

import numpy as np

zeros_array = np.zeros((2,3), dtype = 'int')
print (zeros_array)

[[0 0 0]
 [0 0 0]]


In [ ]:
# Empty NumPy array

empty_array = np.empty((3, 3)) 
print(empty_array)

[[2.72827635e-316 0.00000000e+000 6.92463366e-310]
 [6.92463464e-310 6.92463466e-310 6.92463404e-310]
 [6.92463471e-310 6.92463472e-310 3.95252517e-322]]


In [ ]:
# Full NumPy array

full_array = np.full((2, 3), 6)  
print(full_array)

[[6 6 6]
 [6 6 6]]


In [ ]:
# Numpy array filled with all ones

ones_array = np.ones((2, 3), dtype = 'int')  
print(ones_array)

[[1 1 1]
 [1 1 1]]


In [ ]:
# Combining a one and a two-dimensional NumPy Array

one_dim_array = np.array([1, 2, 3])  
two_dim_array = np.array([[4, 5, 6], [7, 8, 9]])

arr_add = np.vstack((one_dim_array, two_dim_array))
print (arr_add)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Counts the number of non-zero values in the array

array = np.array ([2, 3, 0, 5, 0, 3, 5, 4, 0, 8, 0])

c = np.count_nonzero(array)
print('Total numbers of non-zero values in array: ', c)

Total numbers of non-zero values in array:  7
