<a href="https://colab.research.google.com/github/amitpoa/-Assignment_20231079/blob/main/HOMEWORK__2%5BPandas_and_NumPy_Exercise_for_Data_Analysis%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy Array Exercises**

In [ ]:
# Create a Numpy array filled with all zeros

import numpy as np

zeros_array = np.zeros((2,3), dtype = 'int')
print (zeros_array)

[[0 0 0]
 [0 0 0]]


In [ ]:
# Empty NumPy array

empty_array = np.empty((3, 3))
print(empty_array)

[[4.94e-323 1.58e-322 3.11e-322]
 [1.98e-322 2.47e-323 4.74e-322]
 [2.32e-322 4.00e-322 2.91e-322]]


In [ ]:
# Full NumPy array

full_array = np.full((2, 3), 6)
print(full_array)

[[6 6 6]
 [6 6 6]]


In [ ]:
# Numpy array filled with all ones

ones_array = np.ones((2, 3), dtype = 'int')
print(ones_array)

[[1 1 1]
 [1 1 1]]


In [ ]:
# Combining a one and a two-dimensional NumPy Array

one_dim_array = np.array([1, 2, 3])
two_dim_array = np.array([[4, 5, 6], [7, 8, 9]])

arr_add = np.vstack((one_dim_array, two_dim_array))
print (arr_add)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Counts the number of non-zero values in the array

array = np.array ([2, 3, 0, 5, 0, 3, 5, 4, 0, 8, 0])

c = np.count_nonzero(array)
print('Total numbers of non-zero values in array: ', c)

Total numbers of non-zero values in array:  7


# **NumPy Matrix Exercises**

In [ ]:
import numpy as np

#Maximum value from given matrix

matrix = np.matrix('[10, 32, 63; 40, 15, 96; 47, 81, 59]')

mtx = matrix.max()

print(mtx)


96


In [ ]:
#Minimum value from given matrix

matrix = np.matrix('[10, 32, 63; 40, 5, 96; 47, 81, 59]')
mtx = matrix.min()
print(mtx)

5


In [ ]:
#Find the number of rows and columns

matrix = np.matrix('[10, 32, 63; 40, 5, 96; 47, 81, 59]')
print(matrix.shape)

(3, 3)


In [ ]:
#Matrix Multiplication in NumPy

c = np.matrix([[10, 32],
              [63, 40]])
d = np.matrix([[5, 96],
              [28, 59]])

print(c * d)

[[ 946 2848]
 [1435 8408]]


In [ ]:
#Adding and Subtracting Matrices in Python

c = np.matrix([[10, 32], [63, 40]])
d = np.matrix([[5, 96], [28, 59]])

addition_result = np.add(c, d)
subtraction_result = np.subtract(c, d)

print ('Matrix adding: ')
print (addition_result)

print ('Matrix subtact: ')
print (subtraction_result)

Matrix adding: 
[[ 15 128]
 [ 91  99]]
Matrix subtact: 
[[  5 -64]
 [ 35 -19]]


In [ ]:
#Add row/columns in numpy array

import numpy as np

# Adding rows
c = np.array([[10, 32], [63, 40]])
d = np.array([[50, 96], [28, 59]])
combined_rows = np.vstack((c,d))
print("Combined Rows:")
print(combined_rows)

# Adding columns
e = np.array([[27], [81], [55], [31]])
combined_cols = np.hstack((combined_rows, e))
print("Combined Columns:")
print(combined_cols)

Combined Rows:
[[10 32]
 [63 40]
 [50 96]
 [28 59]]
Combined Columns:
[[10 32 27]
 [63 40 81]
 [50 96 55]
 [28 59 31]]


In [ ]:
#Count the frequency of unique values in NumPy array

import numpy as np

array1 = np.array ([6, 15, 27, 6, 30, 15])

len(np.unique(array1))


4

In [ ]:
#Inverse a matrix

matrix = np.matrix ([[10, 32], [63, 40]])
print ('Inverse matrix')

print (matrix.I)

Inverse matrix
[[-0.02475248  0.01980198]
 [ 0.03898515 -0.00618812]]


In [ ]:
#Calculate the determinant of a matrix

matrix = np.matrix ([[10, 32], [63, 40]])
print (np.linalg.det(matrix))

-1615.9999999999995


In [ ]:
#Convert covariance matrix to correlation matrix using Python

cov_matrix = np.matrix([[2, 1], [1, 2]])
correlation_matrix = np.corrcoef(cov_matrix)
print("Correlation Matrix:")
print(correlation_matrix)

Correlation Matrix:
[[ 1. -1.]
 [-1.  1.]]


# **NumPy Indexing Exercises**

In [ ]:
import numpy as np

#Replace NumPy array elements with condition

array = np.array([1, 2, 3, 4, 5])
condition = array < 3

array[condition] = 0
print(array)

[0 0 3 4 5]


In [ ]:
#Return the indices(indexs')  of elements where the given condition is satisfied

array = np.array ([6, 15, 27, 6, 30, 15])

indices = np.where(array > 12)
print(indices)

(array([1, 2, 4, 5]),)


In [ ]:
#Replace negative value with zero in numpy array

array = np.array([-1, 2, -3, 4, -5])
condition = array < 0
array[condition]=0

print (array)


[0 2 0 4 0]


In [ ]:
#NumPy array at certain index positions

array = np.random.randint(1, 10, size = (1, 7))
print (array)
array[0,3]

[[9 8 2 5 9 8 1]]


5

In [ ]:
# Get the indices where the elements are equal to zero

array = np.array([1, 0, 3, 0, 5])

zero_indices = np.where(array == 0)
print(zero_indices)

(array([1, 3]),)


In [ ]:
# Access different rows of a multidimensional NumPy array?

array = np.random.randint(1, 15, size = (3, 3))
print (array)
array[1,0]

[[14  1 14]
 [ 5  4  4]
 [10  6 12]]


5

In [ ]:
#Remove non-numeric values

import numpy as np


array = np.array([[10.5, np.nan, 22.5], [41, 52.5, np.nan]])

print("Given array:")
print(array)

print("\nRemove all columns containing non-numeric elements ")
print(array[:, ~np.isnan(array).any(axis=0)])

Given array:
[[10.5  nan 22.5]
 [41.  52.5  nan]]

Remove all columns containing non-numeric elements 
[[10.5]
 [41. ]]


In [ ]:
# Get the row numbers with elements larger than X

import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
X = 5
print (np.where(np.any(array > X, axis=1)))

(array([1, 2]),)


# **NumPy Sorting and Searching Exercises**

In [ ]:
import numpy as np

#sorted array by indices

array = np.array([13, 51, 42, 65, 70])
#array = np.array([[13, 51, 21], [42, 65, 70]])
sorted_indices = np.argsort(array)
print(sorted_indices)

[0 2 1 3 4]


In [ ]:
import numpy as np

#Finding the k smallest values of a NumPy array

array = np.array([70, 12, 25, 18, 30, 26, 34])


smallest_values = np.where(array < k)

print(array[smallest_values[:k]])

[12 25 18 26]


In [ ]:
#n-largest values of an array

array = np.array([70, 12, 25, 18, 30, 26, 34])


smallest_values = np.where(array > 30)

print(array[smallest_values[:k]])

[70 34]


In [ ]:
#Sort the values in a matrix

matrix = np.matrix([[70, 12, 25, 18], [30, 26, 34, 55]])

sorted_matrix = np.sort(matrix)
print (sorted_matrix)

[[12 18 25 70]
 [26 30 34 55]]


In [ ]:
#Find the indices into a sorted array

array = np.array([70, 12, 25, 18, 30, 26, 34])
sorted_array = np.sort(array)
print (sorted_array)
sorted_array_by_indices = np.argsort(array)
print (sorted_array_by_indices)

[12 18 25 26 30 34 70]
[1 3 2 5 4 6 0]


# **NumPy Random Exercises**

In [ ]:
#Create a Numpy array with random values

import numpy as np

array = np.random.randint(1, 15, size = (2 , 5))
print (array)

[[ 9 12 10 11  5]
 [ 9 11  6  9  3]]


In [ ]:
#Generate Random Numbers From The Uniform Distribution using NumPy

import numpy as np

random_numbers = np.random.uniform(low=0.0, high=1.0, size=(3) )
print(random_numbers)

[0.24013818 0.50299754 0.2853762 ]


# **Pandas Dataframe Exercises**

In [ ]:
#Make a Pandas DataFrame with two-dimensional list

import pandas as pd

data = [['X', 25], ['Y', 30], ['Z', 35]]
df = pd.DataFrame(data, columns=['Name', 'Age'])
print(df)


  Name  Age
0    X   25
1    Y   30
2    Z   35


In [ ]:
#Creating DataFrame from dict of narray/lists

import pandas as pd

data = {'Name': (['X', 'Y', 'Z']),
        'Age': ([25, 30, 35])}
df = pd.DataFrame(data, index=[''] * len(df))
#df = pd.DataFrame(data)
print(df)


 Name  Age
    X   25
    Y   30
    Z   35


In [ ]:
#Creating a Pandas dataframe using list of tuples

import pandas as pd

data = [('X', 25), ('Y', 30), ('Z', 35)]
df = pd.DataFrame(data, columns=['Name', 'Age'],)
print(df)

  Name  Age
0    X   25
1    Y   30
2    Z   35


In [ ]:
# Creating a dataframe from Pandas series

import pandas as pd

data = ['X','Y', 'Z']
df  = pd.Series(data)
print (df)

0    X
1    Y
2    Z
dtype: object


In [ ]:
#Reindexing in Pandas DataFrame

import pandas as pd

data = {'Name': (['X', 'Y', 'Z']),
        'Age': ([25, 30, 35])}
df  = pd.DataFrame(data, index = [1,2,3] )
print (df)

  Name  Age
1    X   25
2    Y   30
3    Z   35


In [ ]:
#Reset Index in Pandas Dataframe

import pandas as pd

data = {'Name': (['X', 'Y', 'Z']),
        'Age': ([25, 30, 35])}
df  = pd.DataFrame(data, index = [1,2,3] )

df = df.reset_index(drop=True)

print (df)

  Name  Age
0    X   25
1    Y   30
2    Z   35


In [ ]:
#Change column names and row indexes in Pandas DataFrame

data = {'Name': (['X', 'Y', 'Z']),
        'Age': ([25, 30, 35])}
df  = pd.DataFrame(data)

df.columns=['First Name', 'Age']
df.index = [1,2,3]

print (df)

  First Name  Age
1          X   25
2          Y   30
3          Z   35


# **Pandas Dataframe Row Exercises**

In [ ]:
#How to iterate over rows in Pandas Dataframe

import pandas as pd

df = pd.DataFrame({'Name': ['X', 'Y', 'Z'],'Last name': ['A','B','C'], 'Age': [25, 30, 35],
                   'Gender': ['Male', 'Female', 'Male']})

for index in df.index:
    print (df['Name'][index],df['Last name'][index]  )

X A
Y B
Z C


In [ ]:
#Select any row from a Dataframe using iloc[] in Pandas

import pandas as pd

df = pd.DataFrame({'Name': ['X', 'Y', 'Z'],'Last name': ['A','B','C'], 'Age': [25, 30, 35],
                   'Gender': ['Male', 'Female', 'Male']})

for index in range (len(df)):
    print(df.iloc[index, 0], df.iloc[index, 1])

X A
Y B
Z C


In [ ]:
#Select any row from a Dataframe using iat[] in Pandas

import pandas as pd

df = pd.DataFrame({'Name': ['X', 'Y', 'Z'],'Last name': ['A','B','C'], 'Age': [25, 30, 35],
                   'Gender': ['Male', 'Female', 'Male']})

for index in range (len(df)):

        print(df.iat[1,2])

30
30
30


In [ ]:
#Using iterrows() in Pandas

import pandas as pd

df = pd.DataFrame({'Name': ['X', 'Y', 'Z'],'Last name': ['A','B','C'], 'Age': [25, 30, 35],
                   'Gender': ['Male', 'Female', 'Male']})

for i,r in df.iterrows():
    print (r ['Name'],r ['Age'])

X 25
Y 30
Z 35


In [ ]:
#Selecting rows in pandas DataFrame based on conditions

from google.colab import files
uploded= files.upload()

import pandas as pd
import io

data = pd.read_csv(io.BytesIO(uploded['titanic.csv']))

new_df= data[data['Survived']==1]
new_df

Saving titanic.csv to titanic (5).csv


PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
8              9         1       3   
9             10         1       2   
..           ...       ...     ...   
875          876         1       3   
879          880         1       1   
880          881         1       2   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
..                                                 ...     ...   ...    ...   
875                   Najib, Miss. Adele Kiamie "Jane"  female  15.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch            Ticket     Fare Cabin Embarked  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
8        2            347742  11.1333   NaN        S  
9        0            237736  30.0708   NaN        C  
..     ...               ...      ...   ...      ...  
875      0              2667   7.2250   NaN        C  
879      1             11767  83.1583   C50        C  
880      1            230433  26.0000   NaN        S  
887      0            112053  30.0000   B42        S  
889      0            111369  30.0000  C148        C  

[342 rows x 12 columns]

In [ ]:
#Limited rows selection with given column in Pandas  Python

from google.colab import files
uploded= files.upload()

import pandas as pd
import io

data = pd.read_csv(io.BytesIO(uploded['titanic.csv']))

new_df = (data.loc[0:10, ['PassengerId', 'Sex']])
new_df

Saving titanic.csv to titanic (6).csv


PassengerId     Sex
0             1    male
1             2  female
2             3  female
3             4  female
4             5    male
5             6    male
6             7    male
7             8    male
8             9  female
9            10  female
10           11  female

In [ ]:
#Drop rows from the dataframe based on certain condition applied on a column

from google.colab import files
uploded= files.upload()

import pandas as pd
import io

data = pd.read_csv(io.BytesIO(uploded['titanic.csv']))


# new_df = data[data['Sex']=='male']
new_df = data[(data['Sex']=='male')
             & (data['Survived']>=1)]
new_df

Saving titanic.csv to titanic (7).csv


PassengerId  Survived  Pclass                             Name   Sex  \
17            18         1       2     Williams, Mr. Charles Eugene  male   
21            22         1       2            Beesley, Mr. Lawrence  male   
23            24         1       1     Sloper, Mr. William Thompson  male   
36            37         1       3                 Mamee, Mr. Hanna  male   
55            56         1       1                Woolner, Mr. Hugh  male   
..           ...       ...     ...                              ...   ...   
838          839         1       3                  Chip, Mr. Chang  male   
839          840         1       1             Marechal, Mr. Pierre  male   
857          858         1       1           Daly, Mr. Peter Denis   male   
869          870         1       3  Johnson, Master. Harold Theodor  male   
889          890         1       1            Behr, Mr. Karl Howell  male   

      Age  SibSp  Parch  Ticket     Fare Cabin Embarked  
17    NaN      0      0  244373  13.0000   NaN        S  
21   34.0      0      0  248698  13.0000   D56        S  
23   28.0      0      0  113788  35.5000    A6        S  
36    NaN      0      0    2677   7.2292   NaN        C  
55    NaN      0      0   19947  35.5000   C52        S  
..    ...    ...    ...     ...      ...   ...      ...  
838  32.0      0      0    1601  56.4958   NaN        S  
839   NaN      0      0   11774  29.7000   C47        C  
857  51.0      0      0  113055  26.5500   E17        S  
869   4.0      1      1  347742  11.1333   NaN        S  
889  26.0      0      0  111369  30.0000  C148        C  

[109 rows x 12 columns]

In [ ]:
#Insert row at given position in Pandas Dataframe

import pandas as pd

df = pd.DataFrame({'Name': ['X', 'Y', 'Z'],'Last name': ['A','B','C'], 'Age': [25, 30, 35],
                   'Gender': ['Male', 'Female', 'Male']})

df.loc[2.5] = ['G', 'D', 40, 'Male']
df = df.sort_index().reset_index(drop=True)
df



Name Last name  Age  Gender
0    X         A   25    Male
1    Y         B   30  Female
2    Z         C   35    Male
3    G         D   40    Male

In [ ]:
#Create a list from rows in Pandas dataframe

import pandas as pd

df = pd.DataFrame({'Name': ['X', 'Y', 'Z'],'Last name': ['A','B','C'], 'Age': [25, 30, 35],
                   'Gender': ['Male', 'Female', 'Male']})


rows_list = df.values.tolist()
rows_list

[['X', 'A', 25, 'Male'], ['Y', 'B', 30, 'Female'], ['Z', 'C', 35, 'Male']]

In [ ]:
#Ranking Rows of Pandas DataFrame

import pandas as pd

df = pd.DataFrame({'Name': ['X', 'Y', 'Z'],'Last name': ['A','B','C'], 'Age': [25, 30, 35],
                   'Gender': ['Male', 'Female', 'Male']})

df['Rank'] = df['Last name'].rank(ascending = 1)
df = df.set_index('Rank')
# df['Rank'] = df['Age'].rank(ascending = 1)
df


Name Last name  Age  Gender
Rank                            
1.0     X         A   25    Male
2.0     Y         B   30  Female
3.0     Z         C   35    Male

In [ ]:
#Sorting rows in a Pandas DataFrame


import pandas as pd

df = pd.DataFrame({'Name': ['X', 'Y', 'Z'],'Last name': ['A','B','C'], 'Age': [20, 32, 27],
                   'Gender': ['Male', 'Female', 'Male']})

sorted_df=df.sort_values(by='Age', ascending=True)
sorted_df

Name Last name  Age  Gender
0    X         A   20    Male
2    Z         C   27    Male
1    Y         B   32  Female

In [ ]:
#Select row with maximum and minimum value in Pandas dataframe

import pandas as pd

df = pd.DataFrame({'Name': ['X', 'Y', 'Z'],'Last name': ['A','B','C'], 'Age': [20, 32, 27],
                   'Gender': ['Male', 'Female', 'Male']})

print(df.Age.max())
print(df.Age.min())

32
20


In [ ]:
#Get all rows in a Pandas DataFrame containing given substring

import pandas as pd

df = pd.DataFrame({'Name': ['X', 'Y', 'Z'],'Last name': ['A','B','C'], 'Age': [20, 32, 27],
                   'Gender': ['Male', 'Female', 'Male']})

rows_with_substring = df[df['Gender'].str.contains('ma')]  # Select rows where column 'A' contains 'an'
rows_with_substring

Name Last name  Age  Gender
1    Y         B   32  Female

In [ ]:
#Convert a column to row name/index in Pandas

import pandas as pd

df = pd.DataFrame({'Name': ['X', 'Y', 'Z'],'Last name': ['A','B','C'], 'Age': [20, 32, 27],
                   'Gender': ['Male', 'Female', 'Male']})

df = df.set_index('Gender')
df

Name Last name  Age
Gender                    
Male      X         A   20
Female    Y         B   32
Male      Z         C   27

In [ ]:
#Randomly select rows from Pandas DataFrame

from google.colab import files
uploded= files.upload()

import pandas as pd
import io

data = pd.read_csv(io.BytesIO(uploded['titanic.csv']))

data.sample(n=10)

Saving titanic.csv to titanic (8).csv


PassengerId  Survived  Pclass  \
705          706         0       2   
32            33         1       3   
120          121         0       2   
577          578         1       1   
48            49         0       3   
668          669         0       3   
171          172         0       3   
870          871         0       3   
451          452         0       3   
274          275         1       3   

                                               Name     Sex   Age  SibSp  \
705  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.0      0   
32                         Glynn, Miss. Mary Agatha  female   NaN      0   
120                     Hickman, Mr. Stanley George    male  21.0      2   
577       Silvey, Mrs. William Baird (Alice Munger)  female  39.0      1   
48                              Samaan, Mr. Youssef    male   NaN      2   
668                                 Cook, Mr. Jacob    male  43.0      0   
171                            Rice, Master. Arthur    male   4.0      4   
870                               Balkic, Mr. Cerin    male  26.0      0   
451                 Hagland, Mr. Ingvald Olai Olsen    male   NaN      1   
274                      Healy, Miss. Hanora "Nora"  female   NaN      0   

     Parch        Ticket     Fare Cabin Embarked  
705      0        250655  26.0000   NaN        S  
32       0        335677   7.7500   NaN        Q  
120      0  S.O.C. 14879  73.5000   NaN        S  
577      0         13507  55.9000   E44        S  
48       0          2662  21.6792   NaN        C  
668      0      A/5 3536   8.0500   NaN        S  
171      1        382652  29.1250   NaN        Q  
870      0        349248   7.8958   NaN        S  
451      0         65303  19.9667   NaN        S  
274      0        370375   7.7500   NaN        Q

# **Pandas Daraftame Columns Exercises**

In [ ]:
#Create a pandas column using for loop


import pandas as pd

df =  pd.DataFrame({'Name': ['X', 'Y', 'Z'],'Last name': ['A','B','C'],
                    'Gender': ['Male', 'Female', 'Male'], 'Marks': [12, 52, 36]})


result = []
for value in df["Marks"]:
    if value >= 33:
        result.append("Pass")
    elif value < 0 and value > 100:
        result.append("Invalid")
    else:
        result.append("Fail")

df["Result"] = result
df

Name Last name  Gender  Marks Result
0    X         A    Male     12   Fail
1    Y         B  Female     52   Pass
2    Z         C    Male     36   Pass

In [ ]:
#How to get column names in Pandas dataframe

import pandas as pd

df =  pd.DataFrame({'Name': ['X', 'Y', 'Z'],'Last name': ['A','B','C'],
                    'Gender': ['Male', 'Female', 'Male'], 'Marks': [12, 52, 36]})

for i in df.columns:
    print(i)


Name
Last name
Gender
Marks


In [ ]:
#How to rename columns in Pandas DataFrame

import pandas as pd

df =  pd.DataFrame({'Name': ['X', 'Y', 'Z'],'Last name': ['A','B','C'],
                    'Gender': ['Male', 'Female', 'Male'], 'Marks': [12, 52, 36]})

df.rename(columns = {'Marks': 'Result'}, inplace = True)
df

Name Last name  Gender  Result
0    X         A    Male      12
1    Y         B  Female      52
2    Z         C    Male      36

In [ ]:
#Get unique values from a column in Pandas DataFrame

import pandas as pd

df =  pd.DataFrame({'Name': ['X', 'Y', 'Z'],'Last name': ['A','B','C'],
                    'Gender': ['Male', 'Female', 'Male'], 'Marks': [12, 52, 36]})

df.Gender.unique()


array(['Male', 'Female'], dtype=object)

In [ ]:
#Return the Index label if some condition is satisfied over a column in Pandas Dataframe

import pandas as pd

df =  pd.DataFrame({'Name': ['X', 'Y', 'Z'],'Last name': ['A','B','C'],
                    'Gender': ['Male', 'Female', 'Male'], 'Marks': [12, 52, 36]})

df.index =['ID 1', 'ID 2', 'ID 3']

Index_label=df[df['Marks']>20].index.tolist()
print(Index_label)


['ID 2', 'ID 3']


In [ ]:
#Create a new column in Pandas DataFrame based on the existing columns

import pandas as pd

df =  pd.DataFrame({'Frist name': ['X', 'Y', 'Z'],'Last name': ['A','B','C'],
                    'Gender': ['Male', 'Female', 'Male'], 'Marks': [12, 52, 36]})

df['Full name'] = df['Frist name'] + ' '+ df['Last name']

df = df[list(('Frist name', 'Last name', 'Full name', 'Gender', 'Marks' ))]

df

Frist name Last name Full name  Gender  Marks
0          X         A       X A    Male     12
1          Y         B       Y B  Female     52
2          Z         C       Z C    Male     36

In [ ]:
#Getting frequency counts of a columns in Pandas DataFrame

import pandas as pd

df = pd.DataFrame({'A': [21, 23, 19, 17, 12, 15, 15, 17, 17, 19],
                   'B': [ 23, 23, 21, 23, 25, 25, 21, 19, 19, 19]})

count_a = df.groupby(['A']).size()
count_b = df.groupby(['B']).size()


print (count_a)
print (count_b)


A
12    1
15    2
17    3
19    2
21    1
23    1
dtype: int64
B
19    3
21    2
23    3
25    2
dtype: int64


In [ ]:
#Split a text column into two columns in Pandas DataFrame

import pandas as pd

df =  pd.DataFrame({'Name': ['X A', 'Y B', 'Z C'],
                    'Gender': ['Male', 'Female', 'Male'], 'Marks': [12, 52, 36]})

df[['First name','Last name']] = df.Name.str.split(expand=True)

df


Name  Gender  Marks First name Last name
0  X A    Male     12          X         A
1  Y B  Female     52          Y         B
2  Z C    Male     36          Z         C

In [ ]:
#Get the index of minimum value in DataFrame column


import pandas as pd

df = pd.DataFrame({'A': [21, 23, 19, 71, 12, 50, 25, 64, 27, 19],
                   'B': [ 23, 32, 21, 43, 25, 25, 21, 19, 9, 19]})

df['A-B'] = df['A'] - df['B']
df


A   B  A-B
0  21  23   -2
1  23  32   -9
2  19  21   -2
3  71  43   28
4  12  25  -13
5  50  25   25
6  25  21    4
7  64  19   45
8  27   9   18
9  19  19    0

In [ ]:
#How to drop one or multiple columns in Pandas Dataframe

import pandas as pd

df =  pd.DataFrame({'Frist name': ['X', 'Y', 'Z'],'Last name': ['A','B','C'], 'Name': ['X A', 'Y B', 'Z C'],
                    'Gender': ['Male', 'Female', 'Male'], 'Marks': [12, 52, 36]})

df.drop(['Name'], axis=1)


Frist name Last name  Gender  Marks
0          X         A    Male     12
1          Y         B  Female     52
2          Z         C    Male     36

# **Pandas Series – Practice Exercise**

In [ ]:
#Create a Pandas Series from array

import pandas as pd
import numpy as np

array = np.array([1, 2, 3, 4, 5])

series = pd.Series(array)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [ ]:
#Creating a Pandas Series from Dictionary

import pandas as pd

dictionary =pd.Series ({'Frist name': 'X', 'Last name': 'A', 'Gender': 'Male'})

dictionary



Frist name       X
Last name        A
Gender        Male
dtype: object

In [ ]:
#Creating a Pandas Series from Lists

import pandas as pd

lst = [1, 2, 3, 4, 5]

series = pd.Series(lst)
print(series)


0    1
1    2
2    3
3    4
4    5
dtype: int64


In [ ]:
#Access the elements of a Series in Pandas

import pandas as pd

series = pd.Series([1, 2, 3, 4, 5])

print (series[1:4])

1    2
2    3
3    4
dtype: int64


In [2]:
#Convert the column type from string to datetime format in Pandas dataframe

import pandas as pd

df =  pd.DataFrame({'Date':['11/8/2020', '04/23/2020', '10/2/2020'],
                    'First Name': ['X', 'Y', 'Z'],'Last name': ['A','B','C'],
                    'Gender': ['Male', 'Female', 'Male'], 'Marks': [12, 52, 36]})

df['Date']= pd.to_datetime(df['Date'])
df


Date First Name Last name  Gender  Marks
0 2020-11-08          X         A    Male     12
1 2020-04-23          Y         B  Female     52
2 2020-10-02          Z         C    Male     36